{
 "title": "App Info Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "APP_NAME",
    "query": "select distinct SUBSTRING_INDEX(name, ' ', 1) from items where key_ like '%lsof%' and name not like '%APP_NAME%'"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU：$APP_NAME",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*):(.*) cpu/",
        "$1:$2"
       ],
       "text": "replaceAlias(/(.*):(.*) cpu/, $1:$2)"
      },
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "asc" ],
       "text": "sortSeries(asc)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/edu3api*|edu3manage*/" },
     "item": { "filter": "$APP_NAME cpu" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory：$APP_NAME",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*):(.*) cpu/",
        "$1:$2"
       ],
       "text": "replaceAlias(/(.*):(.*) cpu/, $1:$2)"
      },
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "asc" ],
       "text": "sortSeries(asc)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/edu3api*|edu3manage*/" },
     "item": { "filter": "$APP_NAME mem" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LSOF：$APP_NAME",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*):(.*) cpu/",
        "$1:$2"
       ],
       "text": "replaceAlias(/(.*):(.*) cpu/, $1:$2)"
      },
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "asc" ],
       "text": "sortSeries(asc)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/edu3api*|edu3manage*/" },
     "item": { "filter": "$APP_NAME lsof" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}