{
 "title": "Elasticsearch Logstash Redis",
 "tags": [
  "elastic",
  "redis",
  "logstash"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "query": "{\"find\":\"terms\", \"field\":\"_index\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Logstash(in)-CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Elk" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash193" },
     "item": { "filter": "$app_name(_cpu)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logstash(in)-MEM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Elk" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash193" },
     "item": { "filter": "$app_name(_mem)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis-CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Elk" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3redis149" },
     "item": { "filter": "$app_name(_cpu)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis-MEM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Elk" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3redis149" },
     "item": { "filter": "$app_name(_mem)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logstash(out)-CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Elk" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash194" },
     "item": { "filter": "$app_name(_cpu)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logstash(out)-MEM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Elk" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash194" },
     "item": { "filter": "$app_name(_mem)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "一小时各服务器日志数量",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "options": {
      "showDisabledItems": false
     },
     "query": "_index:log-$app_name",
     "timeField": "@timestamp",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "日志数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "options": {
      "showDisabledItems": false
     },
     "query": "_index:(log-)$app_name",
     "timeField": "@timestamp",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "日志总数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Elastic" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3es56" },
     "item": { "filter": "$app_name(_count)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "占用存储",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Elastic" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3es56" },
     "item": { "filter": "$app_name(_size)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logstash(in)-Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "application": { "filter": "Elk" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "desc" ],
       "text": "sortSeries(desc)"
      },
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)_mem/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)_mem/, $1)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash193" },
     "item": { "filter": "/.*_mem/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logstash(out)-Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "application": { "filter": "Elk" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "desc" ],
       "text": "sortSeries(desc)"
      },
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)_mem/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)_mem/, $1)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash194" },
     "item": { "filter": "/.*_mem/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "application": { "filter": "Elastic" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "desc" ],
       "text": "sortSeries(desc)"
      },
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)_size/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)_size/, $1)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3es56" },
     "item": { "filter": "/.*_size/" },
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "options": {
      "showDisabledItems": false
     },
     "timeField": "@timestamp",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logstash(in)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Elk" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash193" },
     "item": { "filter": "ELK process count" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Elk" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3redis149" },
     "item": { "filter": "ELK process count" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logstash(out)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Elk" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash194" },
     "item": { "filter": "ELK process count" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 19 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash193" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 19 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3redis149" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 19 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3logstash194" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Used 56",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3es56" },
     "item": {
      "filter": "Used disk space on /home (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Used 57",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3es57" },
     "item": {
      "filter": "Used disk space on /home (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Kibana",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Kibana" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "sys3deploy64" },
     "item": { "filter": "Kibana process" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}