{
 "title": "Memcached Stats Monitor",
 "tags": [ "memcached" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "OS" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": { "filter": "Host name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "OS" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Mem Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": { "filter": "/Memcached Stats (.*) uptime/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": { "filter": "/Memcached Stats (.*) version/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Libevent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) libevent/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Limit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) limit_maxbytes/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": { "filter": "/Memcached Stats (.*) bytes$/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Hash",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) hash_bytes/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": { "filter": "/Memcached Stats (.*) threads/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Items",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) total_items/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) total_connections/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memcached Stats (.*) cmd_(.*)/",
        "$2"
       ],
       "text": "replaceAlias(/Memcached Stats (.*) cmd_(.*)/, $2)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": { "filter": "/Memcached Stats (.*) cmd_*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memcached Stats (.*) rusage_(.*)/",
        "$2"
       ],
       "text": "replaceAlias(/Memcached Stats (.*) rusage_(.*)/, $2)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) rusage_*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Current Items",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memcached Stats (.*) (.*)/",
        "$2"
       ],
       "text": "replaceAlias(/Memcached Stats (.*) (.*)/, $2)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) curr_items/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memcached Stats (.*) (.*)/",
        "$2"
       ],
       "text": "replaceAlias(/Memcached Stats (.*) (.*)/, $2)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) curr_connections/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memcached Stats (.*) (.*)/",
        "$2"
       ],
       "text": "replaceAlias(/Memcached Stats (.*) (.*)/, $2)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) hit_ratio/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Hits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memcached Stats (.*) (.*)_hits/",
        "$2"
       ],
       "text": "replaceAlias(/Memcached Stats (.*) (.*)_hits/, $2)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": { "filter": "/Memcached Stats (.*) *_hits/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memcached Stats (.*) (.*)_misses/",
        "$2"
       ],
       "text": "replaceAlias(/Memcached Stats (.*) (.*)_misses/, $2)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) *_misses/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memcached" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memcached Stats (.*) bytes_(.*)/",
        "$2"
       ],
       "text": "replaceAlias(/Memcached Stats (.*) bytes_(.*)/, $2)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) bytes_read/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memcached" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memcached Stats (.*) bytes_(.*)/",
        "$2"
       ],
       "text": "replaceAlias(/Memcached Stats (.*) bytes_(.*)/, $2)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "/Memcached Stats (.*) bytes_written/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Eth0",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*) network traffic on eth0/",
        "$1"
       ],
       "text": "replaceAlias(/(.*) network traffic on eth0/, $1)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "Incoming network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*) network traffic on eth0/",
        "$1"
       ],
       "text": "replaceAlias(/(.*) network traffic on eth0/, $1)"
      }
     ],
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "edu3memcached142" },
     "item": {
      "filter": "Outgoing network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}