{
 "title": "Oracle Monitor Global",
 "tags": [
  "oracle",
  "global"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "query": "select h.host from hosts_templates ht, hosts h where ht.templateid=10334 and ht.hostid = h.hostid"
   },
   {
    "name": "host",
    "query": "select h.host from hosts_templates ht, hosts h where ht.templateid=10334 and ht.hostid = h.hostid and h.host like \"$database%\";"
   },
   {
    "name": "hostid",
    "query": "select h.hostid from hosts_templates ht, hosts h where ht.templateid=10334 and ht.hostid = h.hostid and h.host like \"$database%\";"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB Files Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "DB Files Size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "DB Size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Max Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Max Processes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Max Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Max Sessions" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU IO Wait",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU iowait time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Gfs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Free disk /oradata percent" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Archivelog",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Archivelog" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Instance Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Instance Count" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free /Oracle",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select hiu.host, hu.value from (\nSELECT hi.host,hi.name, hi.itemid, max(hu.clock) clock FROM (\nSELECT h.host, i.itemid, i.name FROM items i, hosts h WHERE i.hostid=h.hostid and i.name = \"Free disk space on /oracle\" and h.host like \"$database%\") hi, \nhistory_uint hu WHERE hi.itemid = hu.itemid GROUP BY hi.host, hi.name, hi.itemid DESC) hiu, \nhistory_uint hu WHERE hiu.clock = hu.clock AND hiu.itemid = hu.itemid order by hiu.host",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tablespace Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select a.n name,\nmax(case when a.name like \"% Used Size\" then value else 0 end) used,\n#max(case when a.name like \"% Free Size\" then value else 0 end) free,\nmax(case when a.name like \"% Total Size\" then value else 0 end) total,\nmax(case when a.name like \"% Used Percent\" then value else 0 end) pused\n#max(case when a.name like \"% Free Percent\" then value else 0 end) pfree\nfrom(\nselect substring_index(hi.name, \" \", 1) n, hi.name, hu.value from (select i.name, i.itemid, max(h.clock) clock from \n(select itemid, name from items where hostid = $hostid and name like \"% Size\" and templateid is null) i,\nhistory_uint h where i.itemid = h.itemid group by i.name, i.itemid desc) hi, history_uint hu where hi.clock = hu.clock and hi.itemid = hu.itemid\nunion all\nselect substring_index(hi.name, \" \", 1) n, hi.name, hu.value from (select i.name, i.itemid, max(h.clock) clock from \n(select itemid, name from items where hostid = $hostid and name like \"% Percent\" and templateid is null) i,\nhistory h where i.itemid = h.itemid group by i.name, i.itemid desc) hi, history hu where hi.clock = hu.clock and hi.itemid = hu.itemid\n) a\ngroup by a.n order by a.n",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Big Object List",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select cast(substring_index(tt.context, '##', 1) as char(20)) a,cast(substring_index(substring_index(tt.context, '##', 2), '##', -1) as char(20)) b, cast(substring_index(tt.context, '##', -1) as signed) c from\n(SELECT substring_index(substring_index(t.context, '####', b.help_topic_id + 1), '####', -1) context FROM (\nselect hu.value context from (select i.name, i.itemid, max(h.clock) clock from \n(select itemid, name from items where hostid = \"$hostid\" and name = \"Big Object List\") i,\nhistory_text h where i.itemid = h.itemid group by i.name, i.itemid desc) hi, history_text hu where hi.clock = hu.clock and hi.itemid = hu.itemid) t\nJOIN mysql.help_topic b ON b.help_topic_id < ((LENGTH(t.context) - LENGTH(REPLACE(t.context, '####', '')))/4)) tt\n",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Big Table List",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select cast(substring_index(tt.context, '##', 1) as char(20)) a,cast(substring_index(substring_index(tt.context, '##', 2), '##', -1) as decimal(10,2)) b, cast(substring_index(tt.context, '##', -1) as signed) c from\n(SELECT substring_index(substring_index(t.context, '####', b.help_topic_id + 1), '####', -1) context\nFROM (SELECT hu.value context\nFROM (  SELECT i.name, i.itemid, max(h.clock) clock\nFROM (SELECT itemid, name FROM items  WHERE hostid = \"$hostid\" AND name = \"Oracle Bak Info\") i,\nhistory_text h WHERE i.itemid = h.itemid GROUP BY i.name, i.itemid DESC) hi,\nhistory_text hu WHERE hi.clock = hu.clock AND hi.itemid = hu.itemid) t\nJOIN mysql.help_topic b ON b.help_topic_id < ((LENGTH(t.context) - LENGTH(REPLACE(t.context, '####', '')))/4)) tt",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/$database.*/" },
     "item": { "filter": "/Session total on .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/$database.*/" },
     "item": { "filter": "/Session active on .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "InActive Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/$database.*/" },
     "item": { "filter": "/Session inactive on .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "System Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/$database.*/" },
     "item": { "filter": "/Session system on .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/$database.*/" },
     "item": { "filter": "/Session userconn on .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/$database.*/" },
     "item": { "filter": "/Process on .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Host Access Count",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select cast(substring_index(tt.context, '##', 1) as char(20)) a,cast(substring_index(tt.context, '##', -1) as signed) b from\n(SELECT substring_index(substring_index(t.context, '####', b.help_topic_id + 1), '####', -1) context FROM (\nselect hu.value context from (select i.name, i.itemid, max(h.clock) clock from \n(select itemid, name from items where hostid = \"$hostid\" and name = \"Host Login Count\") i,\nhistory_text h where i.itemid = h.itemid group by i.name, i.itemid desc) hi, history_text hu where hi.clock = hu.clock and hi.itemid = hu.itemid) t\nJOIN mysql.help_topic b ON b.help_topic_id < ((LENGTH(t.context) - LENGTH(REPLACE(t.context, '####', '')))/4)) tt order by 2 desc",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nodes Network",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/$database.*/" },
     "item": {
      "filter": "Incoming network traffic on eth1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "/$database.*/" },
     "item": {
      "filter": "Outgoing network traffic on eth1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "User Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select ttt.a, ttt.b, ttt.c, ttt.d, ttt.e, ttt.f from (select cast(substring_index(tt.context, '##', 1) as char(20)) a,cast(substring_index(substring_index(tt.context, '##', 2), '##', -1) as char(20)) b,\ncast(substring_index(substring_index(tt.context, '##', 3), '##', -1) as signed) c,\ncast(substring_index(substring_index(tt.context, '##', 4), '##', -1) as char(20)) d,\ncast(substring_index(substring_index(tt.context, '##', 5), '##', -1) as signed) e,\ncast(substring_index(tt.context, '##', -1) as char(50)) f from\n(SELECT substring_index(substring_index(t.context, '####', b.help_topic_id + 1), '####', -1) context FROM (\nselect hu.value context from (select i.name, i.itemid, max(h.clock) clock from \n(select itemid, name from items where hostid = \"$hostid\" and name = \"User Info\") i,\nhistory_text h where i.itemid = h.itemid group by i.name, i.itemid desc) hi, history_text hu where hi.clock = hu.clock and hi.itemid = hu.itemid) t\nJOIN mysql.help_topic b ON b.help_topic_id < ((LENGTH(t.context) - LENGTH(REPLACE(t.context, '####', '')))/4)) tt) ttt order by ttt.e",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Busy SQL",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select CONCAT(cast(substring_index(tt.context, '##', 1) as char(2)),':',cast(substring_index(substring_index(tt.context, '##', 2), '##', -1) as char(2000))) b from\n(SELECT substring_index(substring_index(t.context, '####', b.help_topic_id + 1), '####', -1) context FROM (\nselect hu.value context from (select i.name, i.itemid, max(h.clock) clock from \n(select itemid, name from items where hostid = \"$hostid\" and name like \"Busy SQL List%\") i,\nhistory_text h where i.itemid = h.itemid group by i.name, i.itemid desc) hi, history_text hu where hi.clock = hu.clock and hi.itemid = hu.itemid) t\nJOIN mysql.help_topic b ON b.help_topic_id < ((LENGTH(t.context) - LENGTH(REPLACE(t.context, '####', '')))/4)) tt",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bak Date List",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select cast(substring_index(tt.context, '##', 1) as signed) a,cast(substring_index(substring_index(tt.context, '##', 2), '##', -1) as signed) b, cast(substring_index(tt.context, '##', -1) as char(10)) c from\n(SELECT substring_index(substring_index(t.context, '####', b.help_topic_id + 1), '####', -1) context\nFROM (select hu.value context from (select i.name, i.itemid, max(h.clock) clock from \n(select itemid, name from items where hostid = \"$hostid\" and name = \"Oracle Bak List\") i,\nhistory_text h where i.itemid = h.itemid group by i.name, i.itemid desc) hi, history_text hu where hi.clock = hu.clock and hi.itemid = hu.itemid) t\nJOIN mysql.help_topic b ON b.help_topic_id < ((LENGTH(t.context) - LENGTH(REPLACE(t.context, '####', '')))/4)) tt order by 1 desc",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 38 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Free disk space on /home/orabak"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 38 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Total disk space on /home/orabak"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bak Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 38 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Bak" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Oracle Bak Size" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bak Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Bak" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Oracle Bak Count" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bak Latest",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Bak" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Oracle Bak Latest" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bak Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Bak" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Oracle Bak Time" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Centos Servers" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Used disk space on /home/orabak (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GFS Node1 Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT\n  t.clock as time_sec,\n  t.value value,\n  \"Incoming\" as metric\nFROM(\nselect value, clock from history_uint h where h.itemid = (\nselect itemid from items where hostid = (\nselect hostid from hosts where host = \n(select case when \"$database\" like \"%cloud\" then \"edu3gfs19x\" when \"$database\" like \"%act\" then \"edu3gfs25x\" else \"edu3gfs22x\" end host from dual) ) and name = \"Incoming network traffic on eth1\"\n) and clock > UNIX_TIMESTAMP(TIMESTAMPADD(hour,-12,curtime()))\n) t\nORDER BY t.clock ASC",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT\n  t.clock as time_sec,\n  t.value value,\n  \"Outing\" as metric\nFROM(\nselect value, clock from history_uint h where h.itemid = (\nselect itemid from items where hostid = (\nselect hostid from hosts where host = \n(select case when \"$database\" like \"%cloud\" then \"edu3gfs19x\" when \"$database\" like \"%act\" then \"edu3gfs25x\" else \"edu3gfs22x\" end host from dual) ) and name = \"Outgoing network traffic on eth1\"\n) and clock > UNIX_TIMESTAMP(TIMESTAMPADD(hour,-12,curtime()))\n) t\nORDER BY t.clock ASC",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GFS Node2 Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT\n  t.clock as time_sec,\n  t.value value,\n  \"Incoming\" as metric\nFROM(\nselect value, clock from history_uint h where h.itemid = (\nselect itemid from items where hostid = (\nselect hostid from hosts where host = \n(select case when \"$database\" like \"%cloud\" then \"edu3gfs20x\" when \"$database\" like \"%act\" then \"edu3gfs26x\" else \"edu3gfs23x\" end host from dual) ) and name = \"Incoming network traffic on eth1\"\n) and clock > UNIX_TIMESTAMP(TIMESTAMPADD(hour,-12,curtime()))\n) t\nORDER BY t.clock ASC",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT\n  t.clock as time_sec,\n  t.value value,\n  \"Outing\" as metric\nFROM(\nselect value, clock from history_uint h where h.itemid = (\nselect itemid from items where hostid = (\nselect hostid from hosts where host = \n(select case when \"$database\" like \"%cloud\" then \"edu3gfs20x\" when \"$database\" like \"%act\" then \"edu3gfs26x\" else \"edu3gfs23x\" end host from dual) ) and name = \"Outgoing network traffic on eth1\"\n) and clock > UNIX_TIMESTAMP(TIMESTAMPADD(hour,-12,curtime()))\n) t\nORDER BY t.clock ASC",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}